server:
  port: 8768
eureka:
  client:
    service-url:
      defaultZone: http://49.234.99.107:9005/eureka

spring:
  application:
    name: gateway-server
#  redis:
#    host: 127.0.0.1
#    port: 6379
  cloud:
    gateway:
      routes:        # 请求路径匹配
        - id: microservicecloud-provider
          uri: lb://microservicecloud-provider
          predicates:
            - Path=/provider/** # 请求地址携带lhd的,则转发           # 加上StripPrefix=1，否则转发到后端服务时会带上前缀
          filters:
            - StripPrefix=1
        - id: microservicecloud-provider2
            uri: http://49.234.99.107:8002
            predicates:
              - Path=/provider2/** # 请求地址携带lhd的,则转发           # 加上StripPrefix=1，否则转发到后端服务时会带上前缀
            filters:
              - StripPrefix=1
        - id: oauth2-server
          uri: lb://oauth2-server
          predicates:
            - Path=/oauth2/** # 请求地址携带lhd的,则转发           # 加上StripPrefix=1，否则转发到后端服务时会带上前缀
          filters:
            - StripPrefix=1
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION