server:
  port: 18082
eureka:
  client:
    service-url:
      defaultZone: http://49.234.99.107:9005/eureka
spring:
  application:
    name: oauth2-server   # 应用名称
  aop:
    proxy-target-class: true



  # 数据源 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    url: jdbc:mysql://114.215.42.193:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true                    # 数据库名称
    username: root
    password: 123456
    dbcp2:
      initial-size: 5                                         # 初始化连接数
      max-total: 5                                            # 最大连接数
      max-wait-millis: 200                                    # 等待连接获取的最大超时时间
      min-idle: 5                                             # 数据库连接池的最小维持连接数

  redis:
    host: 114.215.42.193
    database: 0


# 不需要拦截的url地址
mySecurity:
  exclude:
    antMatchers: /oauth/**,/login,/home,/ccss

logging:
  level:
    org.springframework.security: DEBUG